### PR TITLE
Sort choices lexicographically

### LINKED ISSUE #50: Does not retain order of results
Steps to reproduce

- `cat file | pick`
- Notice the ordering of the results
- Add some input
- Remove it
- The ordering of the results is not the original anymore

### PR DESCRIPTION
**Pull request by calleerlandsson**
Choices with the same score would be sorted randomly creating an
nondeterministic ordering which confused users.

Choices will now be sorted lexicographically within the same score.

Closes #50

### CODE REVIEW

File: src/choices.c [hunk 1]
```diff
@@ -83,7 +83,9 @@ merge(struct choice *front, struct choice *back)
 	c = &head;
 
 	while (front != NULL && back != NULL) {
-		if (front->score > back->score) {
+		if (front->score > back->score ||
+                (front->score == back->score &&
+                 strcmp(front->str, back->str) < 0)) {
```
Comment (mike-burns) [inline src/choices.c]: It might be faster to use strncmp(3). Or maybe that will just lead to bad results. What do you think?

Comment (calleerlandsson) [inline src/choices.c]: I don't know. What would `n` be? The length of the shortest string? Is that what `strcmp` does?

Comment (mike-burns) [inline src/choices.c]: Yeah, I guess that's what strcmp(3) does. If `front->str` and `back->str` are definitely strings, I guess strcmp(3) is faster.

**Comment by calleerlandsson** [comment]
I will merge this.
